// Catálogo compartido de BiciFast. Usado por catalogo.html, producto.html y carrito.html.
// Cada color puede tener su propio "images" (array de fotos de esa bici en ese color).
// Si un color no trae "images", la ficha de producto usa la galería general del producto.
// "variants" es para bicis que cambian de precio según el tamaño (aro) — cada variante
// puede traer su propia "image". Cuando existe, la ficha muestra un selector que cambia
// el precio y la foto principal.
const BICIFAST_PRODUCTS = [
  {
    id: "bmx-rayo-grueso",
    name: "BMX Rayo Grueso",
    brand: "BiciFast",
    category: "bmx",
    categoryLabel: "Bicicletas BMX",
    price: 399.90,
    oldPrice: null,
    badge: "Nuevo",
    rating: 4.8,
    reviews: 6,
    short: "BMX de eje grueso con 144 rayos y 4 tubos PETS, ideal para trucos y uso urbano.",
    description: "BMX de eje grueso con 144 rayos y 4 tubos PETS. Resistente y ágil, ideal para trucos y uso urbano intenso.",
    image: "img/productos/bmx/bmx-rayo-grueso-azul-399.90.jpg",
    gallery: ["img/productos/bmx/bmx-rayo-grueso-azul-399.90.jpg"],
    colors: [
      { name: "Azul", hex: "#1e5fbf", accent: "#111111", images: ["img/productos/bmx/bmx-rayo-grueso-azul-399.90.jpg"] },
      { name: "Roja", hex: "#c62828", accent: "#111111", images: ["img/productos/bmx/bmx-rayo-grueso-roja-399.90.jpg"] },
      { name: "Verde", hex: "#4caf50", accent: "#111111", images: ["img/productos/bmx/bmx-rayo-grueso-verde-399.90.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Eje": "Grueso", "Rayos": "144", "Tubos": "4 PETS" },
    installments: "Hasta 6 cuotas sin intereses"
  },
  {
    id: "bmx-triple-suspension",
    name: "BMX Triple Suspensión",
    brand: "BiciFast",
    category: "bmx",
    categoryLabel: "Bicicletas BMX",
    price: 490,
    oldPrice: null,
    badge: "Top Ventas",
    rating: 4.9,
    reviews: 9,
    short: "BMX cuadro cromoli con doble freno de disco, aros de aleación magnesio y asiento tipo gel.",
    description: "BMX con cuadro cromoli, doble sistema de frenos de disco, llantas anchas multipropósito, asiento y timón regulable, aros de aleación magnesio, pedales de aluminio, asiento deportivo tipo gel y 4 pets acerados.",
    image: "img/productos/bmx/bmx-triple-suspension-azul-490-1.jpg",
    gallery: [
      "img/productos/bmx/bmx-triple-suspension-azul-490-1.jpg",
      "img/productos/bmx/bmx-triple-suspension-azul-490-2.jpg"
    ],
    colors: [
      { name: "Azul", hex: "#1e5fbf", accent: "#111111", images: ["img/productos/bmx/bmx-triple-suspension-azul-490-1.jpg", "img/productos/bmx/bmx-triple-suspension-azul-490-2.jpg"] },
      { name: "Naranja", hex: "#e67e22", accent: "#111111", images: ["img/productos/bmx/bmx-triple-suspension-naranja-490-1.jpg", "img/productos/bmx/bmx-triple-suspension-naranja-490-2.jpg"] },
      { name: "Verde", hex: "#4caf50", accent: "#111111", images: ["img/productos/bmx/bmx-triple-suspension-verde-490-1.jpg", "img/productos/bmx/bmx-triple-suspension-verde-490-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cuadro": "Cromoli", "Frenos": "Doble sistema de disco", "Llantas": "Anchas multipropósito", "Asiento y timón": "Regulable", "Aros": "Aleación magnesio", "Pedales": "Aluminio", "Pets": "4 pets acerados" },
    installments: "Hasta 6 cuotas sin intereses"
  },
  {
    id: "phillips-p140",
    name: "Phillips P-140",
    brand: "Phillips",
    category: "ninos",
    categoryLabel: "Bicicletas Infantiles",
    price: 250,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 4,
    short: "Bicicleta infantil con parrilla acolchada, canasta forjada y luces auxiliares.",
    description: "Bicicleta infantil con parrilla acolchada, canasta forjada y auxiliares con luces. Ideal para los primeros pedaleos con seguridad y estilo.",
    image: "img/productos/infantiles/p140-aro12-azul-250.jpg",
    gallery: ["img/productos/infantiles/p140-aro12-azul-250.jpg"],
    colors: [],
    variants: [
      { label: "Aro 12 - Azul", price: 250, image: "img/productos/infantiles/p140-aro12-azul-250.jpg" },
      { label: "Aro 12 - Verde", price: 250, image: "img/productos/infantiles/p140-aro12-verde-250.jpg" },
      { label: "Aro 16", price: 280, image: "img/productos/infantiles/p140-aro16-280.jpg" }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Parrilla": "Acolchada", "Canasta": "Forjada", "Luces": "Auxiliares con luces" },
    installments: null
  },
  {
    id: "phillips-p201",
    name: "Phillips P-201",
    brand: "Phillips",
    category: "ninos",
    categoryLabel: "Bicicletas Infantiles",
    price: 250,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 3,
    short: "Bicicleta infantil con parrilla con respaldar, canasta y asiento con resorte.",
    description: "Bicicleta infantil con parrilla con respaldar, canasta, asiento con resorte y protector de cadena. Diseño seguro y cómodo para niños.",
    image: "img/productos/infantiles/p201-aro12-250.jpg",
    gallery: ["img/productos/infantiles/p201-aro12-250.jpg"],
    colors: [],
    variants: [
      { label: "Aro 12", price: 250, image: "img/productos/infantiles/p201-aro12-250.jpg" },
      { label: "Aro 16", price: 280 },
      { label: "Aro 20", price: 300 }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Parrilla": "Con respaldar", "Canasta": "Incluida", "Asiento": "Con resorte", "Protector": "De cadena" },
    installments: null
  },
  {
    id: "phillips-aro20",
    name: "Phillips Aro 20",
    brand: "Phillips",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 350,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Bicicleta aro 20 con suspensión delantera, freno de disco y 18 velocidades.",
    description: "Bicicleta aro 20 con suspensión delantera, freno de disco y sistema de 18 velocidades. Resistente y cómoda para uso diario.",
    image: "img/productos/infantiles/phillips-aro20-350.jpg",
    gallery: ["img/productos/infantiles/phillips-aro20-350.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Suspensión": "Delantera", "Freno": "Disco", "Velocidades": "18" },
    installments: null
  },
  {
    id: "phillips-p132",
    name: "Phillips P-132",
    brand: "Phillips",
    category: "ninos",
    categoryLabel: "Bicicletas Infantiles",
    price: 250,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 5,
    short: "Bicicleta infantil con parrilla acolchada, canasta y protector de cadena, en varios tamaños.",
    description: "Bicicleta infantil con parrilla acolchada, canasta y protector de cadena. Disponible en varios tamaños para acompañar el crecimiento de tu hijo.",
    image: "img/productos/infantiles/phillips-p132-aro12-250.jpg",
    gallery: ["img/productos/infantiles/phillips-p132-aro12-250.jpg"],
    colors: [],
    variants: [
      { label: "Aro 12", price: 250, image: "img/productos/infantiles/phillips-p132-aro12-250.jpg" },
      { label: "Aro 16", price: 280, image: "img/productos/infantiles/phillips-p132-aro16-280.jpg" },
      { label: "Aro 20", price: 300, image: "img/productos/infantiles/phillips-p132-aro20-300.jpg" }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Incluye": "Parrilla acolchada, canasta, protector de cadena" },
    installments: null
  },
  {
    id: "phillips-p136",
    name: "Phillips P-136",
    brand: "Phillips",
    category: "ninos",
    categoryLabel: "Bicicletas Infantiles",
    price: 290,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 4,
    short: "Bicicleta infantil con doble suspensión y luces delanteras y auxiliares.",
    description: "Bicicleta infantil con doble suspensión, luces delanteras y auxiliares con luces, para mayor comodidad y visibilidad.",
    image: "img/productos/infantiles/phillips-p136-aro12-280.jpg",
    gallery: ["img/productos/infantiles/phillips-p136-aro12-280.jpg"],
    colors: [],
    variants: [
      { label: "Aro 12", price: 290, image: "img/productos/infantiles/phillips-p136-aro12-280.jpg" },
      { label: "Aro 16", price: 320, image: "img/productos/infantiles/phillips-p136-aro16-320.jpg" }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Suspensión": "Doble", "Luces": "Delanteras y auxiliares con luces" },
    installments: null
  },
  {
    id: "skys-aluminio-360",
    name: "SKYS",
    brand: "SKYS",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 360,
    oldPrice: null,
    badge: "Top Ventas",
    rating: 4.8,
    reviews: 7,
    short: "Montañera de aluminio con suspensión delantera, frenos de disco y asiento tipo gel.",
    description: "Montañera de estructura y aros de aluminio, con suspensión delantera, llantas anchas, mazas de rodaje de aluminio, sistema de frenos de disco, asiento tipo gel deportivo y timbre integrado a la manija.",
    image: "img/productos/montaneras/skys-aluminio-360-negro-1.jpg",
    gallery: [
      "img/productos/montaneras/skys-aluminio-360-negro-1.jpg",
      "img/productos/montaneras/skys-aluminio-360-negro-2.jpg"
    ],
    colors: [
      { name: "Negro / Azul", hex: "#111111", accent: "#1e88e5", images: ["img/productos/montaneras/skys-aluminio-360-negro-1.jpg", "img/productos/montaneras/skys-aluminio-360-negro-2.jpg"] },
      { name: "Rosado", hex: "#c07fd6", accent: "#f06292", images: ["img/productos/montaneras/skys-aluminio-360-rosado-1.jpg", "img/productos/montaneras/skys-aluminio-360-rosado-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Estructura": "Aluminio", "Suspensión": "Delantera", "Aros": "Aluminio", "Mazas": "Aluminio", "Frenos": "Disco", "Asiento": "Tipo gel deportivo", "Extras": "Timbre integrado a la manija" },
    installments: "Hasta 6 cuotas sin intereses"
  },
  {
    id: "cross-aro12-equilibrio",
    name: "Cross Aro 12 de Equilibrio",
    brand: "Cross",
    category: "ninos",
    categoryLabel: "Bicicletas Infantiles",
    price: 299,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 3,
    short: "Bici de equilibrio sin pedales, cuadro de aleación de magnesio hidroformado, ideal para los primeros pasos en bici.",
    description: "Bicicleta de equilibrio (sin pedales), diseñada para que los niños aprendan a mantener el balance antes de pasar a una bici con pedales. Cuadro de aleación de magnesio hidroformado: liviano y resistente.",
    image: "img/productos/infantiles/cross-aro12-blanca-1.jpg",
    gallery: ["img/productos/infantiles/cross-aro12-blanca-1.jpg", "img/productos/infantiles/cross-aro12-blanca-2.jpg"],
    colors: [
      { name: "Blanca", hex: "#f5f5f5", accent: "#111111", images: ["img/productos/infantiles/cross-aro12-blanca-1.jpg", "img/productos/infantiles/cross-aro12-blanca-2.jpg"] },
      { name: "Violeta", hex: "#8e44ad", accent: "#111111", images: ["img/productos/infantiles/cross-aro12-violeta-1.jpg", "img/productos/infantiles/cross-aro12-violeta-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cuadro": "Aleación de magnesio hidroformado", "Tipo": "Bici de equilibrio (sin pedales)", "Aro": "12" },
    installments: null
  },
  {
    id: "trexx-aro29-doble-suspension",
    name: "Trexx Aro 29 Doble Suspensión",
    brand: "Trex-X",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 750,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 5,
    short: "MTB doble suspensión con cambios Shimano Rapidfire de 21 velocidades y llantas anchas 2.35 Kenda multipropósito.",
    description: "Montañera aro 29 de doble suspensión, equipada con sistema de cambios Shimano Rapidfire de 21 velocidades y llantas anchas 2.35 Kenda multipropósito. Ideal para trocha y uso exigente.",
    image: "img/productos/montaneras/trexx-aro29-azul-1.jpg",
    gallery: ["img/productos/montaneras/trexx-aro29-azul-1.jpg", "img/productos/montaneras/trexx-aro29-azul-2.jpg", "img/productos/montaneras/trexx-aro29-azul-3-cambios.jpg"],
    colors: [
      { name: "Azul", hex: "#1e5fbf", accent: "#111111", images: ["img/productos/montaneras/trexx-aro29-azul-1.jpg", "img/productos/montaneras/trexx-aro29-azul-2.jpg", "img/productos/montaneras/trexx-aro29-azul-3-cambios.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Suspensión": "Doble", "Cambios": "Shimano Rapidfire, 21 velocidades", "Llantas": "Anchas 2.35 Kenda multipropósito", "Aro": "29" },
    installments: null
  },
  {
    id: "fenix-aro29",
    name: "Fénix Aro 29",
    brand: "Fénix",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 599,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 4,
    short: "MTB aro 29 con cuadro hidroformado, 21 velocidades y frenos de disco mecánico.",
    description: "Montañera aro 29 con cuadro hidroformado, sistema de 21 velocidades y frenos de disco mecánico. Ligera y ágil para rutas exigentes.",
    image: "img/productos/montaneras/fenix-roja-1.jpg",
    gallery: ["img/productos/montaneras/fenix-roja-1.jpg", "img/productos/montaneras/fenix-roja-2.jpg"],
    colors: [
      { name: "Roja", hex: "#c62828", accent: "#111111", images: ["img/productos/montaneras/fenix-roja-1.jpg", "img/productos/montaneras/fenix-roja-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cuadro": "Hidroformado", "Velocidades": "21", "Frenos": "Disco mecánico", "Aro": "29" },
    installments: null
  },
  {
    id: "schneider-aro29",
    name: "Schneider Aro 29",
    brand: "Schneider",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 899,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 3,
    short: "MTB full aluminio talla L con sistema de cambios Shimano Altus 8x3 integrado.",
    description: "Montañera aro 29 full aluminio, talla L, con sistema de cambios Shimano Altus 8x3 integrado. Estructura ligera y resistente para rutas largas.",
    image: "img/productos/montaneras/schneider-aro29-amarilla-1.jpg",
    gallery: ["img/productos/montaneras/schneider-aro29-amarilla-1.jpg", "img/productos/montaneras/schneider-aro29-amarilla-2.jpg", "img/productos/montaneras/schneider-aro29-amarilla-3-cambios.jpg"],
    colors: [
      { name: "Amarilla", hex: "#d4d400", accent: "#111111", images: ["img/productos/montaneras/schneider-aro29-amarilla-1.jpg", "img/productos/montaneras/schneider-aro29-amarilla-2.jpg", "img/productos/montaneras/schneider-aro29-amarilla-3-cambios.jpg"] },
      { name: "Roja / Negra", hex: "#c62828", accent: "#111111", images: ["img/productos/montaneras/schneider-aro29-roja-1.jpg", "img/productos/montaneras/schneider-aro29-roja-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Estructura": "Full aluminio", "Talla": "L", "Cambios": "Shimano Altus 8x3 integrado", "Aro": "29" },
    installments: null
  },
  {
    id: "aerofox-aro26-deportiva",
    name: "Aerofox Aro 26 Deportiva",
    brand: "Aerofox",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 290,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 4,
    short: "MTB aro 26 con 18 velocidades tipo moto (gripshift) y aros de aluminio, la opción más accesible.",
    description: "Montañera aro 26 con 18 velocidades tipo moto (gripshift), aros de aluminio y llantas anchas multipropósito. Asiento ligero, pedales de resina y catalina con revestimiento PVC.",
    image: "img/productos/montaneras/aerofox-aro26-azul-1.jpg",
    gallery: ["img/productos/montaneras/aerofox-aro26-azul-1.jpg", "img/productos/montaneras/aerofox-aro26-azul-2.jpg"],
    colors: [
      { name: "Azul", hex: "#1e5fbf", accent: "#111111", images: ["img/productos/montaneras/aerofox-aro26-azul-1.jpg", "img/productos/montaneras/aerofox-aro26-azul-2.jpg"] },
      { name: "Púrpura", hex: "#9c27b0", accent: "#111111", images: ["img/productos/montaneras/aerofox-aro26-purpura-1.jpg", "img/productos/montaneras/aerofox-aro26-purpura-2.jpg"] },
      { name: "Roja", hex: "#c62828", accent: "#111111", images: ["img/productos/montaneras/aerofox-aro26-roja-1.jpg", "img/productos/montaneras/aerofox-aro26-roja-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "18, tipo moto (gripshift)", "Aros": "Aluminio", "Llantas": "Anchas multipropósito", "Asiento": "Ligero", "Pedales": "Resina", "Catalina": "Revestimiento PVC", "Aro": "26" },
    installments: null
  },
  {
    id: "aerofox-aro26-mtb",
    name: "Aerofox Aro 26 MTB",
    brand: "Aerofox",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 399,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 5,
    short: "MTB aro 26 con 18 velocidades tipo moto, frenos v-brake de alta precisión y rueda delantera con liberador rápido.",
    description: "Montañera aro 26 con 18 velocidades tipo moto (gripshift), llantas anchas multipropósito de nylon, asiento acolchado tipo gel ancho, frenos v-brake de alta precisión y rueda delantera con liberador manual rápido. Aros doble pared con rayos negros anticorrosión. Garantía de 3 años en chasis y 1 año de servicio técnico.",
    image: "img/productos/montaneras/aerofox-aro26-mtb-amarilla-1.jpg",
    gallery: ["img/productos/montaneras/aerofox-aro26-mtb-amarilla-1.jpg", "img/productos/montaneras/aerofox-aro26-mtb-amarilla-2.jpg"],
    colors: [
      { name: "Amarilla", hex: "#d4d400", accent: "#111111", images: ["img/productos/montaneras/aerofox-aro26-mtb-amarilla-1.jpg", "img/productos/montaneras/aerofox-aro26-mtb-amarilla-2.jpg"] },
      { name: "Verde", hex: "#4caf50", accent: "#111111", images: ["img/productos/montaneras/aerofox-aro26-mtb-verde-1.jpg", "img/productos/montaneras/aerofox-aro26-mtb-verde-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "18, tipo moto (gripshift)", "Llantas": "Anchas multipropósito de nylon", "Asiento": "Acolchado tipo gel ancho", "Frenos": "V-brake de alta precisión", "Rueda delantera": "Con liberador manual rápido", "Aros": "Doble pared, rayos negros anticorrosión", "Garantía": "3 años en chasis, 1 año de servicio técnico", "Aro": "26" },
    installments: null
  },
  {
    id: "aerofox-aro26-dama",
    name: "Aerofox Aro 26 Montañera Clásica Dama",
    brand: "Aerofox",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 399,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 3,
    short: "MTB aro 26 para dama, cuadro acerado, 18 velocidades tipo moto y ajuste rápido delantero.",
    description: "Montañera aro 26 clásica para dama, con cuadro acerado, 18 velocidades tipo moto, asiento tipo gel, catalina de acero revestida, pedales con rodajes de vaquelita y aros doble pared de aluminio. Ajuste rápido delantero y sistema de frenos v-brake. Garantía de 3 años en chasis y 1 año de servicio técnico.",
    image: "img/productos/montaneras/aerofox-aro26-dama-rosada-1.jpg",
    gallery: ["img/productos/montaneras/aerofox-aro26-dama-rosada-1.jpg", "img/productos/montaneras/aerofox-aro26-dama-rosada-2.jpg"],
    colors: [
      { name: "Rosada", hex: "#e91e8c", accent: "#111111", images: ["img/productos/montaneras/aerofox-aro26-dama-rosada-1.jpg", "img/productos/montaneras/aerofox-aro26-dama-rosada-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "18, tipo moto", "Cuadro": "Acerado", "Asiento": "Tipo gel", "Catalina": "Acero revestida", "Pedales": "Con rodajes de vaquelita", "Aros": "Doble pared, aluminio", "Ajuste delantero": "Rápido", "Frenos": "V-brake", "Garantía": "3 años en chasis, 1 año de servicio técnico", "Aro": "26" },
    installments: null
  },
  {
    id: "mbk-aro20",
    name: "MBK Aro 20",
    brand: "MBK",
    category: "ninos",
    categoryLabel: "Bicicletas Infantiles",
    price: 290,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 3,
    short: "Bicicleta infantil aro 20 importada, con parrilla, canastilla y rayos gruesos de colores.",
    description: "Bicicleta infantil aro 20 importada, con parrilla y canastilla metálicas, luces auxiliares, llantas anchas de nylon, rayos gruesos de colores, asiento tipo gel acolchado y maniguetas ergonómicas. Incluye casco de regalo y timbre tipo chicharra.",
    image: "img/productos/infantiles/mbk-aro20-celeste-1.jpg",
    gallery: ["img/productos/infantiles/mbk-aro20-celeste-1.jpg", "img/productos/infantiles/mbk-aro20-celeste-2.jpg"],
    colors: [
      { name: "Celeste", hex: "#29b6f6", accent: "#111111", images: ["img/productos/infantiles/mbk-aro20-celeste-1.jpg", "img/productos/infantiles/mbk-aro20-celeste-2.jpg"] },
      { name: "Roja", hex: "#c62828", accent: "#111111", images: ["img/productos/infantiles/mbk-aro20-roja-1.jpg", "img/productos/infantiles/mbk-aro20-roja-2.jpg"] },
      { name: "Verde", hex: "#4caf50", accent: "#111111", images: ["img/productos/infantiles/mbk-aro20-verde-1.jpg", "img/productos/infantiles/mbk-aro20-verde-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Origen": "Importada", "Parrilla": "Metálica", "Canastilla": "Metálica", "Luces": "Auxiliares con luces", "Llantas": "Anchas de nylon", "Rayos": "Gruesos, de colores", "Asiento": "Tipo gel acolchado", "Maniguetas": "Ergonómicas", "Incluye": "Casco de regalo y timbre tipo chicharra", "Aro": "20" },
    installments: null
  },
  {
    id: "mbk-aro24-mtb",
    name: "MBK Aro 24 MTB",
    brand: "MBK",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 550,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 3,
    short: "MTB aro 24 con suspensión delantera, frenos de disco y cambios Shimano Tourney 7x3.",
    description: "Montañera aro 24, con sistema de cambios Shimano Tourney 7x3, suspensión delantera con bloqueo manual y control de rebote, frenos de disco, asiento ancho acolchado tipo gel y pedales de aluminio de plataforma ancha. Garantía de 3 años en chasis y 1 año de servicio técnico.",
    image: "img/productos/montaneras/mbk-aro24-mtb-roja-1.jpg",
    gallery: ["img/productos/montaneras/mbk-aro24-mtb-roja-1.jpg", "img/productos/montaneras/mbk-aro24-mtb-roja-2.jpg"],
    colors: [
      { name: "Roja", hex: "#c62828", accent: "#111111", images: ["img/productos/montaneras/mbk-aro24-mtb-roja-1.jpg", "img/productos/montaneras/mbk-aro24-mtb-roja-2.jpg"] },
      { name: "Rosa", hex: "#f06292", accent: "#111111", images: ["img/productos/montaneras/mbk-aro24-mtb-rosa-1.jpg", "img/productos/montaneras/mbk-aro24-mtb-rosa-2.jpg"] },
      { name: "Negra", hex: "#1a1a1a", accent: "#3a3a3a", images: ["img/productos/montaneras/mbk-aro24-mtb-negra-1.jpg", "img/productos/montaneras/mbk-aro24-mtb-negra-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cambios": "Shimano Tourney 7x3", "Asiento": "Ancho, acolchado tipo gel", "Catalina": "Acerada", "Pedales": "Aluminio, plataforma ancha", "Llantas": "Wanda multipropósito nylon", "Maniguetas": "Silicona", "Frenos": "Disco", "Suspensión": "Delantera con bloqueo manual y control de rebote", "Garantía": "3 años en chasis, 1 año de servicio técnico", "Aro": "24" },
    installments: null
  },
  {
    id: "mbk-aro29",
    name: "MBK Aro 29",
    brand: "MBK",
    category: "mtb",
    categoryLabel: "Bicicletas Montañeras (MTB)",
    price: 650,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 3,
    short: "MTB aro 29 con suspensión delantera, frenos de disco y cambios Shimano Tourney 7x3.",
    description: "Montañera aro 29, con sistema de cambios Shimano Tourney 7x3, suspensión delantera con bloqueo manual y control de rebote, frenos de disco, asiento ancho acolchado tipo gel y pedales de aluminio de plataforma ancha. Garantía de 3 años en chasis y 1 año de servicio técnico.",
    image: "img/productos/montaneras/mbk-aro29-negra-1.jpg",
    gallery: ["img/productos/montaneras/mbk-aro29-negra-1.jpg", "img/productos/montaneras/mbk-aro29-negra-2.jpg"],
    colors: [
      { name: "Negra", hex: "#1a1a1a", accent: "#3a3a3a", images: ["img/productos/montaneras/mbk-aro29-negra-1.jpg", "img/productos/montaneras/mbk-aro29-negra-2.jpg"] },
      { name: "Negro / Azul", hex: "#1a1a1a", accent: "#1e5fbf", images: ["img/productos/montaneras/mbk-aro29-negro-azul-1.jpg", "img/productos/montaneras/mbk-aro29-negro-azul-2.jpg"] },
      { name: "Plomo", hex: "#9e9e9e", accent: "#111111", images: ["img/productos/montaneras/mbk-aro29-plomo-1.jpg", "img/productos/montaneras/mbk-aro29-plomo-2.jpg"] },
      { name: "Roja", hex: "#c62828", accent: "#111111", images: ["img/productos/montaneras/mbk-aro29-roja-1.jpg", "img/productos/montaneras/mbk-aro29-roja-2.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cambios": "Shimano Tourney 7x3", "Asiento": "Ancho, acolchado tipo gel", "Catalina": "Acerada", "Pedales": "Aluminio, plataforma ancha", "Llantas": "Wanda multipropósito nylon", "Maniguetas": "Silicona", "Frenos": "Disco", "Suspensión": "Delantera con bloqueo manual y control de rebote", "Garantía": "3 años en chasis, 1 año de servicio técnico", "Aro": "29" },
    installments: null
  },
  {
    id: "maza-arc7075-tb115",
    name: "Par de Mazas ARC/7075 TB115",
    brand: "ARC",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 290,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 2,
    short: "Par de mazas MTB ARC/7075 TB115, aleación 7075, con cierre rápido y acabado tornasolado.",
    description: "Par de mazas para MTB, modelo ARC/7075 TB115, en aleación de aluminio 7075 con acabado tornasolado. Incluyen cierre rápido delantero y trasero.",
    image: "img/productos/accesorios/maza-arc7075-mt009-tornasol.jpg",
    gallery: ["img/productos/accesorios/maza-arc7075-mt009-tornasol.jpg"],
    colors: [
      { name: "Tornasol (MT009)", hex: "#8e44ad", accent: "#111111", images: ["img/productos/accesorios/maza-arc7075-mt009-tornasol.jpg"] },
      { name: "Lila (MT039)", hex: "#b455d9", accent: "#111111", images: ["img/productos/accesorios/maza-arc7075-mt039-lila.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Aleación de aluminio 7075", "Modelo": "TB115", "Cierre": "Rápido, delantero y trasero", "Uso": "MTB" },
    installments: null
  },
  {
    id: "pedal-rockbros-amarillo",
    name: "Pedales Rockbros Amarillo",
    brand: "Rockbros",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 90,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Pedales de aluminio con punteras delgadas, para MTB.",
    description: "Pedales Rockbros de aluminio, con punteras delgadas, ideales para MTB. Livianos y resistentes.",
    image: "img/productos/accesorios/pedal-rockbros-amarillo.jpg",
    gallery: ["img/productos/accesorios/pedal-rockbros-amarillo.jpg"],
    colors: [
      { name: "Amarillo", hex: "#f9a825", accent: "#111111", images: ["img/productos/accesorios/pedal-rockbros-amarillo.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Aluminio", "Punteras": "Delgadas", "Uso": "MTB" },
    installments: null
  },
  {
    id: "pedal-rockbros-rojo",
    name: "Pedales Rockbros Rojo",
    brand: "Rockbros",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 90,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 2,
    short: "Pedales de aleación de aluminio y fibra de magnesio, ultra delgados y ligeros, para MTB.",
    description: "Pedales Rockbros de aleación de aluminio y fibra de magnesio, ultra delgados y ligeros. Ideales para MTB.",
    image: "img/productos/accesorios/pedal-rockbros-rojo.jpg",
    gallery: ["img/productos/accesorios/pedal-rockbros-rojo.jpg"],
    colors: [
      { name: "Rojo", hex: "#c62828", accent: "#111111", images: ["img/productos/accesorios/pedal-rockbros-rojo.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Aleación de aluminio y fibra de magnesio", "Peso": "Ultra ligero", "Uso": "MTB" },
    installments: null
  },
  {
    id: "pedal-xm-resina",
    name: "Pedales XM Resina",
    brand: "XM",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 65,
    oldPrice: null,
    badge: null,
    rating: 4.5,
    reviews: 3,
    short: "Pedales de resina ultra resistente, ultra delgados y multifuncionales, para MTB.",
    description: "Pedales XM de resina ultra resistente, ultra delgados y multifuncionales. Ideales para MTB.",
    image: "img/productos/accesorios/pedal-xm-azul.jpg",
    gallery: ["img/productos/accesorios/pedal-xm-azul.jpg"],
    colors: [
      { name: "Azul", hex: "#2f7fb3", accent: "#111111", images: ["img/productos/accesorios/pedal-xm-azul.jpg"] },
      { name: "Azul Oscuro", hex: "#1d5a73", accent: "#111111", images: ["img/productos/accesorios/pedal-xm-azul-oscuro.jpg"] },
      { name: "Naranja", hex: "#e8551a", accent: "#111111", images: ["img/productos/accesorios/pedal-xm-naranja.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Resina ultra resistente", "Uso": "MTB multifuncional" },
    installments: null
  },
  {
    id: "maza-koozer-xm490",
    name: "Mazas Posteriores Koozer XM490",
    brand: "Koozer",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 240,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Maza posterior tipo casetero Koozer XM490, disponible en 2 colores.",
    description: "Maza posterior tipo casetero, modelo Koozer XM490. Disponible en color rojo o aluminio.",
    image: "img/productos/accesorios/maza-koozer-xm490.jpg",
    gallery: ["img/productos/accesorios/maza-koozer-xm490.jpg"],
    colors: [
      { name: "Rojo", hex: "#c62828", accent: "#111111", images: ["img/productos/accesorios/maza-koozer-xm490.jpg"] },
      { name: "Aluminio", hex: "#c0c0c0", accent: "#111111", images: ["img/productos/accesorios/maza-koozer-xm490.jpg"] }
    ],
    sizes: [],
    unavailableSizes: [],
    specs: { "Tipo": "Casetero", "Modelo": "XM490", "Posición": "Posterior" },
    installments: null
  },
  {
    id: "inflador-bom-mi-x-truper",
    name: "Inflador BOM-MI-X Truper",
    brand: "Truper",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 28,
    oldPrice: null,
    badge: null,
    rating: 4.5,
    reviews: 2,
    short: "Inflador portátil de cuerpo de aluminio, ligero y versátil.",
    description: "Inflador Truper modelo BOM-MI-X, cuerpo de aluminio portátil, ligero y versátil.",
    image: "img/productos/accesorios/inflador-bom-mi-x-truper.jpg",
    gallery: ["img/productos/accesorios/inflador-bom-mi-x-truper.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cuerpo": "Aluminio", "Tipo": "Portátil" },
    installments: null
  },
  {
    id: "inflador-giyo",
    name: "Inflador Giyo",
    brand: "Giyo",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 30,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Inflador portátil de cuerpo de aluminio, ligero, práctico y muy resistente.",
    description: "Inflador Giyo, cuerpo de aluminio portátil. Ligero, práctico y muy resistente. Hecho en Taiwán.",
    image: "img/productos/accesorios/inflador-giyo.jpg",
    gallery: ["img/productos/accesorios/inflador-giyo.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Cuerpo": "Aluminio", "Tipo": "Portátil", "Origen": "Taiwán" },
    installments: null
  },
  {
    id: "catalina-slx-shimano",
    name: "Catalina SLX Shimano",
    brand: "Shimano",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 550,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 2,
    short: "Catalina Shimano SLX, eje botón, monoplato 34T.",
    description: "Catalina Shimano SLX, con eje de botón y configuración monoplato de 34 dientes.",
    image: "img/productos/accesorios/catalina-slx-shimano.jpg",
    gallery: ["img/productos/accesorios/catalina-slx-shimano.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Eje": "Botón", "Configuración": "Monoplato", "Dientes": "34T" },
    installments: null
  },
  {
    id: "catalina-shimano-montaneras",
    name: "Catalina Shimano para Montañeras",
    brand: "Shimano",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 70,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Catalina Shimano de aluminio resistente, triple plato 48/36/28T.",
    description: "Catalina Shimano para montañeras, de aluminio resistente, triple plato 48/36/28T.",
    image: "img/productos/accesorios/catalina-shimano-montaneras.jpg",
    gallery: ["img/productos/accesorios/catalina-shimano-montaneras.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Aluminio resistente", "Configuración": "Triple plato", "Dientes": "48/36/28T" },
    installments: null
  },
  {
    id: "catalina-aluminio-atom",
    name: "Catalina de Aluminio Atom",
    brand: "Atom",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 280,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Catalina de aluminio Atom, eje botón, monoplato 36T.",
    description: "Catalina de aluminio marca Atom, eje de botón, configuración monoplato de 36 dientes.",
    image: "img/productos/accesorios/catalina-aluminio-atom.jpg",
    gallery: ["img/productos/accesorios/catalina-aluminio-atom.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Aluminio", "Eje": "Botón", "Configuración": "Monoplato", "Dientes": "36T" },
    installments: null
  },
  {
    id: "catalina-sunrace-juju-m90",
    name: "Catalina Sunrace JuJu M90",
    brand: "Sunrace",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 65,
    oldPrice: null,
    badge: null,
    rating: 4.5,
    reviews: 2,
    short: "Catalina Sunrace de aluminio, eje cuadrado, triple plato.",
    description: "Catalina Sunrace, modelo JuJu M90, eje cuadrado, aluminio triple plato.",
    image: "img/productos/accesorios/catalina-sunrace-juju-m90.jpg",
    gallery: ["img/productos/accesorios/catalina-sunrace-juju-m90.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Material": "Aluminio", "Eje": "Cuadrado", "Configuración": "Triple plato", "Modelo": "JuJu M90" },
    installments: null
  },
  {
    id: "pinon-shimano-6v",
    name: "Piñón Shimano 6 Velocidades",
    brand: "Shimano",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 40,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Piñón Shimano dorado de 6 velocidades, modelo MF-TZ500-6.",
    description: "Piñón Shimano dorado, 6 velocidades, modelo MF-TZ500-6.",
    image: "img/productos/accesorios/pinon-shimano-6v.jpg",
    gallery: ["img/productos/accesorios/pinon-shimano-6v.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "6", "Modelo": "MF-TZ500-6", "Color": "Dorado" },
    installments: null
  },
  {
    id: "pinon-shimano-7v",
    name: "Piñón Shimano 7 Velocidades",
    brand: "Shimano",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 50,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 2,
    short: "Piñón Shimano dorado de 7 velocidades, modelo MF-TZ500-7.",
    description: "Piñón Shimano dorado, 7 velocidades, modelo MF-TZ500-7.",
    image: "img/productos/accesorios/pinon-shimano-7v.jpg",
    gallery: ["img/productos/accesorios/pinon-shimano-7v.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "7", "Modelo": "MF-TZ500-7", "Color": "Dorado" },
    installments: null
  },
  {
    id: "pinon-shimano-casetero-8v",
    name: "Piñón Casetero Shimano 8 Velocidades",
    brand: "Shimano",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 75,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 2,
    short: "Piñón casetero Shimano negro, 8 velocidades, Megarange 34T Hyperglide.",
    description: "Piñón casetero Shimano, negro, 8 velocidades, modelo CS-HG31-8, Megarange 34T Hyperglide HG.",
    image: "img/productos/accesorios/pinon-shimano-casetero-8v.jpg",
    gallery: ["img/productos/accesorios/pinon-shimano-casetero-8v.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "8", "Modelo": "CS-HG31-8", "Sistema": "Megarange 34T Hyperglide HG", "Color": "Negro" },
    installments: null
  },
  {
    id: "pinon-casetero-sypo-8v",
    name: "Piñón Casetero SYPO 8 Velocidades",
    brand: "SYPO",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 55,
    oldPrice: null,
    badge: null,
    rating: 4.5,
    reviews: 2,
    short: "Piñón casetero SYPO de 8 velocidades, cierre Lock 40N·m.",
    description: "Piñón casetero SYPO, 8 velocidades, cierre tipo Lock 40N·m.",
    image: "img/productos/accesorios/pinon-casetero-sypo-8v.jpg",
    gallery: ["img/productos/accesorios/pinon-casetero-sypo-8v.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "8", "Marca": "SYPO", "Cierre": "Lock 40N·m" },
    installments: null
  },
  {
    id: "pinon-shimano-10v",
    name: "Piñón Shimano 10 Velocidades",
    brand: "Shimano",
    category: "accesorios",
    categoryLabel: "Accesorios y Repuestos",
    price: 150,
    oldPrice: null,
    badge: null,
    rating: 4.7,
    reviews: 2,
    short: "Piñón Shimano acerado HG de 10 velocidades, 36/32/28/24/21/19/17/15/13/11T.",
    description: "Piñón Shimano acerado HG, fabricado en Japón, 10 velocidades: 36/32/28/24/21/19/17/15/13/11T.",
    image: "img/productos/accesorios/pinon-shimano-10v.jpg",
    gallery: ["img/productos/accesorios/pinon-shimano-10v.jpg"],
    colors: [],
    sizes: [],
    unavailableSizes: [],
    specs: { "Velocidades": "10", "Material": "Acerado HG", "Origen": "Japón", "Dientes": "36/32/28/24/21/19/17/15/13/11T" },
    installments: null
  }
];

function formatPEN(amount) {
  return "S/ " + amount.toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function getProductById(id) {
  return BICIFAST_PRODUCTS.find((p) => p.id === id);
}
